@extends('layouts/homepage')

@section('title', $data['page_title'])
@section('content')

  <section>
    <div class="w-100 pt-60 position-relative">
      <div class="fixed-bg" style="background-image: url(/homepage/images/bg10.jpg);"></div>
      <div class="container">
        <div class="page-title-wrap text-center w-100 d-inline-block">
          <div class="page-title-inner d-inline-block">
            <h2 class="mb-0 text-color7">{{$data['page_title']}}</h2>
          </div>
          <div class="breadcrumbs-wrap w-100">
            <ul class="breadcrumbs mb-0 list-unstyled d-inline-flex">
              <li><a href="/" title="Home">Home</a></li>
              <li class="active">{{$data['page_title']}}</li>
            </ul><!-- Breadcrumbs -->
          </div>
        </div><!-- Page Title Wrap -->
      </div>
    </div>
  </section>
  <section>
    <div class="w-100 pt-50">
      <div class="container">
        <div class="port-detail-img-wrap w-100 mt-40">
          <div class="port-detail-img-caro text-center">
            <div><img class="img-fluid brd-rd20" src="/homepage/images/resources/port-detail-img3-1.jpg"
                      alt="Portfolio Detail Image 1"></div>
            <div><img class="img-fluid brd-rd20" src="/homepage/images/resources/port-detail-img3-2.jpg"
                      alt="Portfolio Detail Image 2"></div>
            <div><img class="img-fluid brd-rd20" src="/homepage/images/resources/port-detail-img3-3.jpg"
                      alt="Portfolio Detail Image 3"></div>
          </div>
        </div>
        <div class="port-detail-wrap w-100 mb-5">
        {!! $data['content'] !!}
        <!-- <div class="port-detail-desc mt-40 w-100">
					<h2 class="mb-0">What Is 3-D Secure Authentication ?</h2>
					<p class="mb-0">Non odio in, phasellus risus et sed sit ac proin, sit ut at elit nam laoreet, tempor elit a per vitae. Eu facilisis gravida faucibus erat blandit justo, molestiae in dapibus, consectetuer justo purus et congue. Vulputate pellentesque consequat, pede in. Quis ut tincidunt ut, nec accumsan pede elit mollis, fringilla facilisis leo quis, luctus pede. Morbi et sagittis lacus cursus convallis, nostra tortor id arcu nam etiam enim, laborum et a, neque libero nunc. A hac facilisi est morbi, pede per. </p>
				</div>
				<div class="port-detail-desc mt-40 w-100">
					<h2 class="mb-0">Authentication procedure:</h2>
					<p>After entering your bank details on the payment page, you are redirected to a page generated by your bank to verify the identity of the card holder.
						The authentication process is specific to each bank. You may be asked to:
					</p>
					<p>Enter your date of birth</p>
					<p>Enter a code received via SMS</p>
					<p>Respond to a personal question</p>
					<p>After confirmation from your bank, your payment is validated and the status of your reservation is confirmed on the TRIPSER page.</p>
					<p>When ordering, be sure that you are able to receive 3-D Secure authentication by SMS (operator restriction, international order, network coverage, etc.)</p>
					<p>Verify that your contact phone number at your bank is still active.</p>
				</div>
			</div> -->
        </div>
      </div>
  </section>
@endsection
